blog_name: "Cenk Corapci"
introduction: "Hello ðŸ‘‹. I'm Cenk. A data engineer living in the Netherlands."
base_url: "https://cenkcorapci.com"
linkedin_url: "https://linkedin.com/in/cenkcorapci"
github_url: "https://github.com/cenkcorapci/my-blog"
